export const projects = [
  {
    title: 'Smart Grid Analytics Platform',
    category: 'Power Systems',
    description: "AI-powered analytics platform for real-time power grid monitoring with predictive maintenance capabilities. Processes over 10TB of SCADA data daily to optimize grid reliability and prevent outages.",
    problem: "Traditional power grid monitoring systems were reactive, leading to unexpected outages and maintenance costs. Manual analysis of grid data was time-consuming and prone to human error.",
    solution: "Developed a comprehensive analytics platform using machine learning algorithms to predict equipment failures, optimize load distribution, and provide real-time insights to grid operators.",
    image: '/images/1.png',
    tags: ['Python', 'TensorFlow', 'SCADA', 'PostgreSQL', 'React', 'Docker'],
    metrics: '40% reduction in unplanned outages',
    source: 'https://github.com/kennethez/smart-grid-analytics',
    visit: 'https://smart-grid-demo.vercel.app/',
    status: 'Production',
    id: 0,
  },
  {
    title: 'Blockchain Energy Trading System',
    category: 'Blockchain',
    description: "Decentralized peer-to-peer energy trading platform enabling consumers to buy and sell excess renewable energy directly. Features smart contracts for automated settlements and real-time energy tracking.",
    problem: "Centralized energy markets limited opportunities for renewable energy producers to monetize excess production. Complex intermediary processes increased costs and reduced efficiency.",
    solution: "Built a blockchain-based platform using Ethereum smart contracts to enable direct energy trading between prosumers, with automated pricing and settlement mechanisms.",
    image: '/images/2.png',
    tags: ['Solidity', 'Web3.js', 'React', 'Node.js', 'IPFS', 'Ethereum'],
    metrics: '25% cost reduction for participants',
    source: 'https://github.com/kennethez/energy-trading-blockchain',
    visit: 'https://energy-trading-demo.vercel.app/',
    status: 'Production',
    id: 1,
  },
  {
    title: 'AI Infrastructure Monitoring',
    category: 'AI/ML',
    description: "Machine learning-powered infrastructure monitoring system that predicts equipment failures and optimizes maintenance schedules for critical power transmission equipment.",
    problem: "Infrastructure failures in power transmission systems caused significant financial losses and service disruptions. Preventive maintenance was either over-scheduled or missed critical issues.",
    solution: "Implemented IoT sensors and ML algorithms to continuously monitor equipment health, predict failures with 95% accuracy, and optimize maintenance scheduling to reduce costs.",
    image: '/images/3.jpg',
    tags: ['Python', 'TensorFlow', 'IoT', 'AWS', 'Time Series Analysis', 'Flask'],
    metrics: '30% reduction in maintenance costs',
    source: 'https://github.com/kennethez/ai-infrastructure-monitor',
    visit: 'https://ai-monitor-demo.vercel.app/',
    status: 'Production',
    id: 2,
  },
  {
    title: 'Digital Twin Control System',
    category: 'Digital Twin',
    description: "Advanced digital twin platform for power plant operations with real-time 3D visualization, predictive analytics, and remote control capabilities for enhanced operational efficiency.",
    problem: "Power plant operators lacked comprehensive real-time visibility into complex systems, making it difficult to optimize performance and predict maintenance needs effectively.",
    solution: "Created a digital twin using Three.js for 3D visualization, integrated with real-time sensor data and ML models to provide operators with complete system visibility and predictive insights.",
    image: '/images/4.jpg',
    tags: ['Three.js', 'Python', 'WebGL', 'Real-time Data', 'Machine Learning', 'WebSockets'],
    metrics: '20% improvement in operational efficiency',
    source: 'https://github.com/kennethez/digital-twin-power',
    visit: 'https://digital-twin-demo.vercel.app/',
    status: 'Production',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'BSc. Electrical & Electronics Engineering - Federal University of Technology Owerri' },
  { year: 2018, text: 'Data Analyst - Transmission Infrastructure' },
  { year: 2019, text: 'Operations Manager - Surelink Computers Ltd' },
  { year: 2020, text: 'IBM Applied AI Professional Certificate & Cloud Computing Specialization' },
  { year: 2021, text: 'Founded Tech Consulting Practice & Advanced Cybersecurity Certifications' },
  { year: 2022, text: 'Senior Systems Engineer - Cloud Infrastructure & DevOps Specialist' },
  { year: 2023, text: 'Technical Lead - AI/ML Implementation & Digital Transformation' },
  { year: 2024, text: 'Principal Engineer - Full-Stack Development & Blockchain Solutions' },
  { year: 2025, text: 'Innovation Director - Leading Digital Infrastructure Projects' },
];