export const projects = [
  {
    title: 'Crypto Application',
    description: "Connect your wallet and send crypto currencies accross the internet to anywhere in the world. Fast, Safe and Secured",
      image: '/images/krypt.png',
      tags: ['React', 'Web3', 'Solidity '],
    source: 'https://hardcore-bose-8cb86d.netlify.app/',
    visit: 'https://hardcore-bose-8cb86d.netlify.app/',
    id: 0,
  },
  {
    title: 'Nft Profile Dapp',
    description: "Connect your wallet and view your nft collection anywhere in the world ",
      image: '/images/nft.png',
      tags: ['React', 'Web3', 'Solidity '],
    source: 'https://affectionate-villani-368a75.netlify.app/',
    visit: 'https://affectionate-villani-368a75.netlify.app/',
    id: 1,
  },
  {
    title: 'Virtual Banking ',
    description:"Unique and complex bank site app that you will be able to add to use. And trust me, banking systems apps and applications are impressive.",
    image: '/images/virtual.png',
    tags: ['React', 'JavaScript'],
    source: 'https://vigilant-noyce-ab94e6.netlify.app/',
    visit: 'https://vigilant-noyce-ab94e6.netlify.app/',
    id: 2,
  },
  {
    title: 'Smart-Brain App ',
    description:"Complex app where you can login and upload pictures where numbers of faces can be scanned and numbered. You know how many people in the pictures and also retrive counts ",
    image: '/images/smart-brain.png',
    tags: ['React', 'JavaScript'],
    source: 'https://smartbrain20.herokuapp.com/',
    visit: 'https://smartbrain20.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Robo Friends ',
    description: "Using React, Node.js, Express & MongoDB One of my first applications where you can generate random colorful robo faces and do with them as you please.",
      image: '/images/robo.png',
      tags: ['Html', 'Css', 'React', 'MongoDB'],
    source: 'https://roboappbyken.herokuapp.com/',
    visit: 'https://roboappbyken.herokuapp.com/',
    id: 4,
  },
  
  {
    title: 'Gradient Generator',
    description: "One of my first applications where you can generate colorful gradients just by selecting colors. Impressive right?",
    image: '/images/gradient.png',
    tags: ['Html', 'Css', ],
    source: 'https://stupefied-edison-d9ea3a.netlify.app/',
    visit: 'https://stupefied-edison-d9ea3a.netlify.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Bsc. Electrical Electronics Engineering ', },
  { year: 2018, text: 'Data Analyst with Transmission Company of Nigeria', },
  { year: 2019, text: 'Operations Manager with Surelink Computers', },
  { year: 2020, text: 'IBM Applied Artificial Intelligence', },
  { year: 2021, text: 'Started my own platform', },
];