export const projects = [
  {
    title: 'AI-Powered Analytics Dashboard',
    description: "Modern analytics dashboard with AI-driven insights and real-time data visualization. Built with Next.js, TypeScript, and integrated machine learning models for predictive analytics.",
    image: '/images/analytics-dashboard.png',
    tags: ['Next.js', 'TypeScript', 'AI/ML', 'D3.js', 'Python'],
    source: 'https://github.com/kennethez/ai-analytics-dashboard',
    visit: 'https://ai-analytics-dashboard.vercel.app/',
    id: 0,
  },
  {
    title: 'Cloud Infrastructure Automation',
    description: "DevOps automation platform for cloud infrastructure management with Terraform, AWS, and monitoring capabilities. Reduces deployment time by 80%.",
    image: '/images/cloud-automation.png',
    tags: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'Python'],
    source: 'https://github.com/kennethez/cloud-automation',
    visit: 'https://cloud-automation-demo.vercel.app/',
    id: 1,
  },
  {
    title: 'Blockchain Supply Chain Tracker',
    description: "Transparent supply chain management system using blockchain technology. Track products from origin to consumer with immutable records and smart contracts.",
    image: '/images/supply-chain.png',
    tags: ['Solidity', 'Web3', 'React', 'Ethereum', 'IPFS'],
    source: 'https://github.com/kennethez/blockchain-supply-chain',
    visit: 'https://supply-chain-tracker.vercel.app/',
    id: 2,
  },
  {
    title: 'IoT Energy Management System',
    description: "Smart energy monitoring and optimization system for industrial applications. Real-time monitoring, predictive maintenance, and energy efficiency optimization.",
    image: '/images/iot-energy.png',
    tags: ['IoT', 'Python', 'React', 'MongoDB', 'Machine Learning'],
    source: 'https://github.com/kennethez/iot-energy-system',
    visit: 'https://iot-energy-demo.vercel.app/',
    id: 3,
  },
  {
    title: 'Cybersecurity Risk Assessment Platform',
    description: "Comprehensive cybersecurity risk assessment and monitoring platform with automated threat detection and compliance reporting.",
    image: '/images/cybersecurity.png',
    tags: ['Python', 'FastAPI', 'React', 'PostgreSQL', 'Docker'],
    source: 'https://github.com/kennethez/cyber-risk-platform',
    visit: 'https://cyber-risk-assessment.vercel.app/',
    id: 4,
  },
  {
    title: 'Digital Twin Manufacturing System',
    description: "Advanced digital twin platform for manufacturing optimization using real-time data, 3D visualization, and predictive analytics.",
    image: '/images/digital-twin.png',
    tags: ['Three.js', 'Python', 'React', 'WebGL', 'TensorFlow'],
    source: 'https://github.com/kennethez/digital-twin-manufacturing',
    visit: 'https://digital-twin-demo.vercel.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'BSc. Electrical & Electronics Engineering - Federal University of Technology Owerri' },
  { year: 2018, text: 'Data Analyst - Transmission Infrastructure' },
  { year: 2019, text: 'Operations Manager - Surelink Computers Ltd' },
  { year: 2020, text: 'IBM Applied AI Professional Certificate & Cloud Computing Specialization' },
  { year: 2021, text: 'Founded Tech Consulting Practice & Advanced Cybersecurity Certifications' },
  { year: 2022, text: 'Senior Systems Engineer - Cloud Infrastructure & DevOps Specialist' },
  { year: 2023, text: 'Technical Lead - AI/ML Implementation & Digital Transformation' },
  { year: 2024, text: 'Principal Engineer - Full-Stack Development & Blockchain Solutions' },
  { year: 2025, text: 'Innovation Director - Leading Digital Infrastructure Projects' },
];